language: scala

scala:
  - 2.10.5
  - 2.11.7

addons:
  postgresql: "9.3"

before_script:
  - psql -c "CREATE ROLE root WITH SUPERUSER LOGIN PASSWORD '';" -U postgres
  - psql -c "CREATE DATABASE akka_persistence_sql_async;" -U postgres
  - mysql -e "CREATE DATABASE akka_persistence_sql_async;" -uroot
